CREATE TABLE Country (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(120) UNIQUE NOT NULL,
    code VARCHAR(128) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);